export { default as Layout } from './Layout'
export { default as Home } from './pages/Home'
export { default as Profil } from './pages/Profil'
export { default as Carte } from './pages/Carte'
export { default as Loading } from './pages/Loading'
export { default as History } from './pages/History'